name: gh-pages
permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  gh-pages:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Generate
        run: yarn generate

      - name: Generate
        run: yarn deploy
